name: firebase_cloud_firestore
description: "Simplify the serialization of objects for cloud_firestore in a Flutter app. It streamlines the process of converting Dart objects into formats compatible with cloud_firestore, making data storage and retrieval smoother and more efficient for developers."
version: 4.15.8
homepage: https://landamessenger.com
repository: https://github.com/landamessenger/firebase_cloud_firestore

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.8                      # android   ios           macos   web
  object: ^1.0.2                                # android   ios   linux   macos   web   windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
